# Generated by Django 4.2 on 2023-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
    ]
