# Generated by Django 4.2.1 on 2023-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_aksiyon_movie_gerilim_movie_korku_movie_macera'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dram',
            field=models.BooleanField(default=False),
        ),
    ]
